language: c
cache:
  directories:
    - ../lean
dist: trusty
addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:kalakris/cmake' # cmake 2.8 for precise
      - sourceline: 'ppa:adrozdoff/cmake' # cmake 3 for trusty
      - sourceline: 'ppa:h-rayflood/llvm'
      - sourceline: ppa:hvr/z3   # z3 for the smt interface package
    packages: &default_packages
      - cmake
      - libgmp-dev
      - libgoogle-perftools-dev
      - g++-4.9
      - clang-3.4
matrix:
  include:
   - os: linux
     dist: precise
     env:
       CMAKE_CXX_COMPILER=g++-4.9
       CMAKE_BUILD_TYPE=Release
install: ./install-dependencies.sh
script: ./verify-fabstracts.sh
